import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Naive Bayes Text Classifier</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
    </div>
  )
}

export default Home;

export function NavBar() {
  return (
    <nav>
      <h4>
        Naive Bayes Classifier
      </h4>
    </nav>
  );
}
